SPACING_XS = 4
SPACING_SM = 6
SPACING_MD = 12
SPACING_LG = 16
SPACING_XL = 24

ENTRY_HEIGHT = 28
BUTTON_HEIGHT = 28
BUTTON_HEIGHT_SM = 24
BUTTON_HEIGHT_MD = 32
NAVBAR_HEIGHT = 44
NAVBAR_PADDING_X = 12
NAVBAR_PADDING_Y = 4
SUMMARY_BAR_HEIGHT = 26
STATUS_BAR_HEIGHT = 24

RADIUS_SM = 4
RADIUS_MD = 6
RADIUS_LG = 8

CARD_PADX = 12
CARD_PADY_TOP = 0
CARD_PADY_BOTTOM = 8
INNER_PADX = 8
SIDEBAR_WIDTH = 200
NAV_SIDEBAR_WIDTH = 150
CLIENT_SIDEBAR_WIDTH = 150

MODAL_WIDTH_SM = 400
MODAL_WIDTH_MD = 480
MODAL_WIDTH_LG = 800
MODAL_HEIGHT_MD = 400
MODAL_HEIGHT_LG = 600

DROPDOWN_WIDTH_MD = 200
DROPDOWN_WIDTH_SM = 160
INPUT_WIDTH_WIDE = 280
INPUT_WIDTH_MD = 160
ICON_BUTTON_WIDTH = 32
ICON_BUTTON_WIDTH_SM = 32
ICON_BUTTON_WIDTH_LG = 40

ACTION_BUTTON_WIDTH = 115
ACTION_BUTTON_WIDTH_SM = 100
ACTION_BUTTON_WIDTH_MD = 140
ACTION_BUTTON_WIDTH_LG = 160
ACTION_BUTTON_WIDTH_XL = 180

CHECKBOX_SIZE = 20
CHECKBOX_SIZE_SM = 18
PROGRESS_BAR_HEIGHT = 4
PROGRESS_BAR_WIDTH = 120
DIVIDER_HEIGHT = 1
SIDEBAR_BUTTON_HEIGHT = 32
MODAL_SECTION_HEIGHT = 56

TOOLTIP_DELAY_MS = 500
FOOTER_PADDING_X = 12
FOOTER_PADDING_Y = 6
